			<fieldset class="ezUser-fieldset">
				<div id="ezUser-message" class="ezUser-message" onclick="ezUser_click(this)"><p class="ezUser-message-fail">Check username &amp; password</p></div>
				<input id="ezUser-signin" value="Sign in"
					tabindex	=	"3204"
					type		=	"button"
					class		=	"ezUser-button ezUser-action ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<input id="ezUser-goaccount" value="Register"
					tabindex	=	"3203"
					type		=	"button"
					class		=	"ezUser-button ezUser-action ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
			</fieldset>
			<fieldset class="ezUser-fieldset">
				<input id="ezUser-staySignedIn" value="Stay signed in"
					tabindex	=	"3207"
					type		=	"button"
					class		=	"ezUser-button ezUser-preference ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<input id="ezUser-rememberMe" value="Remember me"
					tabindex	=	"3206"
					type		=	"button"
					class		=	"ezUser-button ezUser-preference ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<input id="ezUser-reminder" value="Reset password"
					tabindex	=	"3205"
					type		=	"button"
					class		=	"ezUser-button ezUser-preference ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
			</fieldset>
		</form>]]></ezUser>