				<input id= "ezUser-account-password"
					tabindex	=	"3215"
					value		=	"************"
					type		=	"password"
					onfocus		=	"ezUser_passwordFocus(this)"
					onblur		=	"ezUser_passwordBlur(this)"
					class		=	"ezUser-text"
					onkeyup		=	"ezUser_keyUp(event)"
					size		=	"40"
				/>
				<label class="ezUser-label" for="ezUser-account-password">* Password:</label>
				<input id= "ezUser-account-confirm"
					tabindex	=	"3216"
					value		=	"************"
					type		=	"password"
					onfocus		=	"ezUser_passwordFocus(this)"
					onblur		=	"ezUser_passwordBlur(this)"
					class		=	"ezUser-text"
					onkeyup		=	"ezUser_keyUp(event)"
					size		=	"40"
				/>
				<label class="ezUser-label" for="ezUser-account-confirm">* Confirm password:</label>