				<label class="ezUser-label" for="ezUser-account-email">* Email address:</label>
				<input id= "ezUser-account-firstName"
					tabindex	=	"3212"
					value		=	"Dominic"
					type		=	"text"
					class		=	"ezUser-text"
					onkeyup		=	"ezUser_keyUp(event)"
					size		=	"40"
				/>
				<label class="ezUser-label" for="ezUser-account-firstName">First name:</label>
				<input id= "ezUser-account-lastName"
					tabindex	=	"3213"
					value		=	"Sayers"
					type		=	"text"
					class		=	"ezUser-text"
					onkeyup		=	"ezUser_keyUp(event)"
					size		=	"40"
				/>
				<label class="ezUser-label" for="ezUser-account-lastName">Last name:</label>