<ezUser container="ezUser"><![CDATA[		<form id="ezUser-dashboard-form" class="ezUser-form" onsubmit="return false">
			<fieldset class="ezUser-fieldset">
				<input id="ezUser-signout" value="Sign out"
					tabindex	=	"3222"
					type		=	"button"
					class		=	"ezUser-button ezUser-preference ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<input id="ezUser-goaccount" value="My account"
					tabindex	=	"3221"
					type		=	"button"
					class		=	"ezUser-button ezUser-preference ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<div id="ezUser-fullName" class="ezUser-fullName">Dominic _Z*! - Sayers</div>
			</fieldset>
			<fieldset class="ezUser-fieldset">
				<div id="ezUser-message" class="ezUser-message" onclick="ezUser_click(this)"><p class="ezUser-message-hidden"></p></div>
			</fieldset>
		</form>]]></ezUser>