			<fieldset class="ezUser-fieldset">
				<div id="ezUser-account-message" class="ezUser-message" onclick="ezUser_click(this)"><p class="ezUser-message-plain">* = mandatory field</p></div>
				<input id="ezUser-account-validate" value="OK"
					tabindex	=	"3217"
					type		=	"button"
					class		=	"ezUser-button ezUser-action ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
				<input id="ezUser-account-cancel" value="Cancel"
					tabindex	=	"3218"
					type		=	"button"
					class		=	"ezUser-button ezUser-action ezUser-buttonstate-0"
					onclick		=	"ezUser_click(this)"
					onmouseover	=	"ezUser_setButtonState(this, 1, true)"
					onmouseout	=	"ezUser_setButtonState(this, 1, false)"
					onfocus		=	"ezUser_setButtonState(this, 2, true)"
					onblur		=	"ezUser_setButtonState(this, 2, false)"
				/>
			</fieldset>